version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: giorgiovola
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 4050:5432